---
kind: pipeline
name: ftdc-tools
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.9
  pull: if-not-exists
  commands:
  - pip3 install --upgrade pip
  - pip3 install poetry==1.2.0
  - poetry --version
  - poetry install
  - poetry run pytest src tests
  when:
    branch:
      - main
    event:
      - pull_request
      - push
- name: publish
  image: python:3.9
  pull: if-not-exists
  environment:
    PYPI_TOKEN:
      from_secret: PYPI_TOKEN
  commands:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  - . $HOME/.poetry/env
  - poetry config pypi-token.pypi $PYPI_TOKEN
  - poetry publish --build
  when:
    branch:
      - main
    event:
      - push
